# /etc/fail2ban/filter.d/vulnera-generic.conf
# Filter untuk mendeteksi berbagai anomali dan serangan umum dari access.log

[Definition]

# Setiap baris di bawah ini adalah pola regex terpisah untuk serangan yang berbeda.
# Fail2Ban akan memeriksa setiap baris log terhadap SEMUA pola ini.
failregex = ^<HOST> .* "POST /login HTTP/1.1" 302 .*
            ^<HOST> .* "GET .* HTTP/1.1" 404 .*
            ^<HOST> .* "GET .* HTTP/1.1" 200 .*() { :;};.*
            ^<HOST> .* "GET .* HTTP/1.1" 200 .*' OR 1=1 --.*
